import type { Product } from "./types";

const PRODUCT_IMAGES: Record<string, string> = {
  "hausbrot": "/products/brot-dinkel-1.webp",
  "vollkorn-saftkorn": "/products/brot-roggen-1.webp",
  "schwarzbrot": "/products/brot-roggen-2.webp",
  "kartoffel-dinkelkruste": "/products/brot-dinkel-1.webp",
  "baguette": "/products/brot-dinkel-1.webp",
  "walnuss-dattelbrot": "/products/brot-roggen-1.webp",
  "roggenbauer": "/products/brot-roggen-2.webp",
  "koernerkruste": "/products/brot-dinkel-1.webp",
  "dinkelstueck": "/products/brot-dinkel-1.webp",
  "dinkel-toast": "/products/brot-dinkel-1.webp",
  "pures-hafer": "/products/brot-roggen-1.webp",
  "pain-artisan": "/products/brot-roggen-2.webp",
  "bauernlaib": "/products/brot-dinkel-1.webp",
  "hausbroetchen": "/products/broetchen-laugenbrezel-1.webp",
  "laugenbrezel": "/products/broetchen-laugenbrezel-2.webp",
  "laugenzopf": "/products/broetchen-laugenstange-1.webp",
  "kaesedings": "/products/broetchen-laugenstange-2.webp",
  "oliven-dinkelstange": "/products/broetchen-laugenstange-3.webp",
  "schoko-dinkelstange": "/products/broetchen-laugenstange-4.webp",
  "walnussweck": "/products/broetchen-laugenstange-5.webp",
  "schweizer-buerli": "/products/broetchen-laugenbrezel-3.webp",
  "dinkel-vollkornbroetchen": "/products/broetchen-laugenbrezel-2.webp",
  "koernerbroetchen": "/products/broetchen-laugenstange-5.webp",
  "sauerteigweck": "/products/broetchen-laugenbrezel-3.webp",
  "zimtschnecke": "/products/suess-streuselkuchen-1.webp",
  "kaesekuchen": "/products/suess-kaesekuchen-1.webp",
  "brownie": "/products/suess-brownie-1.webp",
  "streuselkuchen": "/products/suess-streuselkuchen-2.webp",
  "himbeer-schnecke": "/products/suess-streuselkuchen-3.webp",
  "apfel-zimtschnecke": "/products/suess-streuselkuchen-4.webp",
  "schokoschnecke": "/products/suess-brownie-2.webp",
  "walnuss-ahorn-schnecke": "/products/suess-streuselkuchen-5.webp",
  "apfel-mandel-schnecke": "/products/suess-streuselkuchen-6.webp",
  "kardamomknopf": "/products/suess-streuselkuchen-7.webp",
  "rosinenknoten": "/products/suess-kaesekuchen-2.webp",
  "schokoweck": "/products/suess-brownie-3.webp",
  "schoko-nuss-baba": "/products/suess-brownie-4.webp",
  "brioche": "/products/suess-kaesekuchen-3.webp",
  "carrot-cake": "/products/suess-kaesekuchen-4.webp",
  "mandelmurmel": "/products/suess-brownie-5.webp",
  "schlemmertasche": "/products/snacks-deli-2.webp",
  "laugenkorn-schinken-kaese": "/products/snacks-deli-3.webp",
  "avocado-bagel": "/products/snacks-deli-5.webp",
  "classique-tomate-ei": "/products/snacks-deli-4.webp",
  "dinkel-plus-kaese": "/products/snacks-deli-6.webp",
  "wikinger-pute": "/products/snacks-deli-7.webp",
  "baeckwich-florida": "/products/snacks-deli-8.webp",
  "brotzeit-omelett": "/products/snacks-deli-2.webp",
  "classique-frikadelle": "/products/snacks-deli-1.webp",
  "classique-pute": "/products/snacks-deli-8.webp",
  "caffe-crema": "/products/getraenke-kaffee-1.webp",
  "americano": "/products/getraenke-kaffee-2.webp",
  "cappuccino": "/products/getraenke-kaffee-3.webp",
  "caffe-crema-mild-bohnen": "/products/getraenke-kaffee-4.webp",
  "caramel-macchiato": "/products/getraenke-caramel-macchiato-1.webp",
  "iced-caramel": "/products/getraenke-caramel-macchiato-2.webp",
  "iced-schoko": "/products/getraenke-kaffee-5.webp",
  "mango-lassi": "/products/getraenke-caramel-macchiato-3.webp",
  "chai-latte": "/products/getraenke-chai-latte-1.webp",
  "earl-grey": "/products/getraenke-chai-latte-2.webp",
  "erdbeer-vanille": "/products/feinkost-geschenkkorb-1.webp",
  "habichtswald-honig": "/products/feinkost-honig-1.webp",
  "knabbermix": "/products/feinkost-knabbermix-2.webp",
  "backmischung-sauerteig": "/products/feinkost-geschenkkorb-3.webp",
  "geschenkkorb": "/products/feinkost-geschenkkorb-2.webp",
  "kaffee-bohnen": "/products/feinkost-geschenkkorb-4.webp",
};

export const demoProducts: Product[] = [
  product("hausbrot", "bread", "Hausbrot", 450, "750g", "Weizenmischbrot mit Dinkelsauerteig und 24 Stunden Teigführung.", ["A"], ["hausgemacht", "beliebt", "täglich"], true, false),
  product("vollkorn-saftkorn", "bread", "Vollkorn-Saftkorn", 520, "750g", "Saftiges Vollkornbrot aus Roggen und Dinkel mit Saaten.", ["A", "H", "N"], ["vollkorn", "gesund"], true, false),
  product("kartoffel-dinkelkruste", "bread", "Kartoffel-Dinkelkruste", 490, "750g", "Dinkelmischbrot mit Kartoffelflocken und kräftiger Steinofenkruste.", ["A"], ["dinkel", "saftig"], true, false),
  product("baguette", "bread", "Baguette", 380, "350g", "Weizenbaguette mit Vorteig, langer Gehzeit und knuspriger Kruste.", ["A"], ["französisch", "knusprig"], true, false),
  product("walnuss-dattelbrot", "bread", "Walnuss-Dattelbrot", 590, "750g", "Weizenmischbrot mit gerösteten Walnüssen und Datteln.", ["A", "H"], ["nussig", "premium"], true, false),
  product("roggenbauer", "bread", "Roggenbauer", 550, "1000g", "Roggenmischbrot mit Sauerteig, Dinkelanteil und Fenchel.", ["A"], ["sauerteig", "hefefrei"], true, false),
  product("koernerkruste", "bread", "Körnerkruste", 470, "750g", "Kerniges Weizenmischbrot mit Leinsaat, Hafer und Sesam.", ["A", "N"], ["kernig", "ballaststoffreich"], true, false),
  product("dinkelstueck", "bread", "Dinkelstück", 590, "750g", "Saftiges Dinkelvollkornbrot mit Brühstück und Sesamkruste.", ["A", "N"], ["dinkel", "vollkorn"], true, false),
  product("dinkel-toast", "bread", "Dinkel-Toast", 450, "500g", "Mildes Dinkelbrot mit Flohsamenschalen und Sesam.", ["A", "N"], ["toast", "mild"], true, false),
  product("schwarzbrot", "bread", "Schwarzbrot", 590, "1000g", "Roggenvollkornbrot mit Sauerteig, Edelkakao und Rübensirup.", ["A"], ["vollkorn", "dunkel"], true, false),
  product("pures-hafer", "bread", "Pures Hafer", 550, "750g", "Kastenbrot aus Haferflocken und Hafersauerteig.", ["A"], ["hafer", "mild"], true, false),
  product("pain-artisan", "bread", "Pain Artisan", 490, "750g", "Weizenbrot mit französischem Vorteig und grober Porung.", ["A"], ["französisch", "handwerklich"], true, false),
  product("bauernlaib", "bread", "Bauernlaib", 520, "1000g", "Rustikaler Roggenmischlaib mit Sauerteig und Fenchel.", ["A"], ["sauerteig", "rustikal"], true, false),
  product("hausbroetchen", "rolls", "Hausbrötchen", 90, "Stück", "Knuspriges Brötchen mit grober Porung und langer Teigführung.", ["A"], ["klassisch", "beliebt"], true, false),
  product("walnussweck", "rolls", "Walnussweck", 120, "Stück", "Lockeres Brötchen mit 17 Prozent Walnüssen.", ["A", "H"], ["nussig", "knusprig"], true, false),
  product("sauerteigweck", "rolls", "Sauerteigweck", 130, "Stück", "Kerniges Brötchen mit Saaten und Natursauerteig.", ["A", "N"], ["sauerteig", "kernig"], true, false),
  product("dinkel-vollkornbroetchen", "rolls", "Dinkel-Vollkornbrötchen", 140, "Stück", "Nussiges Dinkelvollkornbrötchen mit Kürbiskernen.", ["A"], ["dinkel", "vollkorn"], true, false),
  product("koernerbroetchen", "rolls", "Körnerbrötchen", 120, "Stück", "Kerniges Brötchen mit Saaten, Hafer und kräftiger Kruste.", ["A", "N"], ["kernig", "ballaststoffreich"], true, false),
  product("schweizer-buerli", "rolls", "Schweizer Bürli", 130, "Stück", "Steinofenbrötchen mit grober Porung und säuerlichem Aroma.", ["A"], ["steinofen", "schweizerisch"], true, false),
  product("kaesedings", "rolls", "Käsedings", 180, "Stück", "Saftige Käsestange mit Gouda, Kürbiskernen und Gewürzen.", ["A", "G"], ["herzhaft", "snack"], true, false),
  product("laugenzopf", "rolls", "Laugenzopf", 150, "Stück", "Von Hand geflochtener Laugenzopf mit grobem Salz.", ["A"], ["lauge", "handgefertigt"], true, false),
  product("laugenbrezel", "rolls", "Laugenbrezel", 150, "Stück", "Von Hand geschlungene Brezel mit Laugengeschmack und grobem Salz.", ["A"], ["lauge", "beliebt"], true, false),
  product("oliven-dinkelstange", "rolls", "Oliven-Dinkelstange", 190, "Stück", "Veganer Snack aus Dinkelmehl mit grünen Oliven.", ["A"], ["vegan", "snack"], true, false),
  product("schoko-dinkelstange", "rolls", "Schoko-Dinkelstange", 190, "Stück", "Veganer Dinkelsnack mit Zartbitterschokolade.", ["A", "H"], ["vegan", "schokolade"], true, false),
  product("zimtschnecke", "sweets", "Zimtschnecke", 320, "Stück", "Luftiger Hefeteig mit hauseigener Zimt-Butter-Füllung.", ["A", "C", "G"], ["süß", "beliebt"], true, false),
  product("himbeer-schnecke", "sweets", "Weiße Schoko-Himbeer-Schnecke", 380, "Stück", "Hefeteig mit weißer Schokolade und Himbeeren.", ["A", "C", "G"], ["süß", "neu"], true, false),
  product("apfel-zimtschnecke", "sweets", "Apfel-Zimtschnecke", 350, "Stück", "Hefeteig mit Zimtfüllung und saftigen Apfelstücken.", ["A", "C", "G"], ["süß", "fruchtig"], true, false),
  product("schokoschnecke", "sweets", "Schokoschnecke", 350, "Stück", "Saftige Hefeschnecke mit Zartbitterschokolade.", ["A", "C", "G"], ["süß", "schokolade"], true, false),
  product("walnuss-ahorn-schnecke", "sweets", "Walnuss-Ahorn-Schnecke", 390, "Stück", "Hefeschnecke mit Walnüssen und Ahornsirup.", ["A", "C", "G", "H"], ["nussig", "premium"], true, false),
  product("apfel-mandel-schnecke", "sweets", "Apfel-Mandel-Schnecke", 350, "Stück", "Vegane Schnecke mit Äpfeln, Zimt und Mandelstiften.", ["A", "H"], ["vegan", "fruchtig"], true, false),
  product("kardamomknopf", "sweets", "Kardamomknopf", 320, "Stück", "Geflochtener Hefeteig mit Kardamom-Butter-Mischung.", ["A", "C", "G"], ["gewürzig", "skandinavisch"], true, false),
  product("rosinenknoten", "sweets", "Rosinenknoten", 320, "Stück", "Fluffiger Hefeteig mit Milch, Butter und Sultaninen.", ["A", "C", "G"], ["klassisch", "süß"], true, false),
  product("schokoweck", "sweets", "Schokoweck", 250, "Stück", "Saftiger Hefeteig mit Zartbitterschokolade.", ["A", "C", "G"], ["schokolade", "beliebt"], true, false),
  product("schoko-nuss-baba", "sweets", "Schoko-Nuss-Baba", 420, "Stück", "Veganes Dinkelgebäck mit Kakao-Haselnusscreme.", ["A", "H"], ["vegan", "premium"], true, false),
  product("brioche", "sweets", "Brioche", 280, "Stück", "Französischer Klassiker aus Weizenmehl, Milch und Butter.", ["A", "C", "G"], ["französisch", "klassisch"], true, false),
  product("carrot-cake", "sweets", "Carrot Cake", 450, "Stück", "Dinkelkuchen mit Karotten, Walnüssen und Frischkäsecreme.", ["A", "C", "G", "H"], ["fruchtig", "nussig"], true, false),
  product("brownie", "sweets", "Brownie", 450, "Stück", "Reichhaltiger Kuchen mit Butter, Schokolade und Meersalz.", ["A", "C", "G"], ["schokolade", "beliebt"], true, false),
  product("streuselkuchen", "sweets", "Streuselkuchen", 380, "Stück", "Saisonales Obst auf Hefeteig mit Butterstreuseln.", ["A", "C", "G"], ["saisonal", "fruchtig"], true, false),
  product("kaesekuchen", "sweets", "Käsekuchen", 420, "Stück", "Cremiger Kuchen mit Streuselboden, Sahne und Vanille.", ["A", "C", "G"], ["cremig", "klassisch"], true, false),
  product("mandelmurmel", "sweets", "Mandelmurmel", 280, "Stück", "Vegane Kugel aus Marzipan, Mandeln und Dinkelmehl.", ["A", "H"], ["vegan", "mandel"], true, false),
  product("americano", "drinks", "Caffè Americano", 320, "0,3l", "Verlängerter Espresso mit goldener Crema.", [], ["heiß", "kaffee", "vegan"], false, true),
  product("caffe-crema", "drinks", "Caffè Crema", 350, "0,2l", "Frisch gemahlener Kaffee mit milder Crema.", [], ["heiß", "kaffee", "vegan", "beliebt"], false, true),
  product("caffe-crema-mild-bohnen", "drinks", "Caffè Crema Mild Bohnen", 1290, "500g", "Milde Arabica-Bohnen für zu Hause.", [], ["kaffee", "vegan", "zum-mitnehmen"], false, true),
  product("cappuccino", "drinks", "Cappuccino", 380, "0,25l", "Espresso mit Milch oder Haferdrink und feinem Schaum.", ["G"], ["heiß", "kaffee", "vegan-option"], false, true),
  product("caramel-macchiato", "drinks", "Caramel Macchiato", 450, "0,3l", "Espresso mit Milch, Vanille und Karamell.", ["G"], ["heiß", "süß", "premium"], false, true),
  product("iced-caramel", "drinks", "Iced Caramel Caffè", 450, "0,4l", "Eiskaffee mit Milch oder Haferdrink und Karamell.", ["G"], ["kalt", "sommer", "vegan-option"], false, true),
  product("iced-schoko", "drinks", "Iced Schoko", 420, "0,4l", "Kalte Schokomilch auf Crushed Ice.", ["G"], ["kalt", "schokolade"], false, true),
  product("mango-lassi", "drinks", "Mango Lassi", 450, "0,4l", "Fruchtiger Mango-Trinkjoghurt auf Crushed Ice.", ["G"], ["kalt", "fruchtig"], false, true),
  product("chai-latte", "drinks", "Chai Latte", 420, "0,3l", "Gewürztee mit Zimt, Kardamom, Ingwer und Milch.", ["G"], ["heiß", "gewürzig"], false, true),
  product("earl-grey", "drinks", "Earl Grey Tee", 350, "0,4l", "Schwarzer Tee mit Bergamotte und frischer Zitronennote.", [], ["tee", "vegan"], false, true),
  product("laugenkorn-schinken-kaese", "snacks", "Laugenkorn Schinken & Käse", 390, "Stück", "Laugensnack mit Käse, Kochschinken, Leinsamen und Sesam.", ["A", "G", "N"], ["herzhaft", "mittag"], true, false),
  product("schlemmertasche", "snacks", "Schlemmertasche", 350, "Stück", "Käsebrötchen mit Kochschinken, Käse, Remoulade und Salat.", ["A", "C", "F", "G"], ["beliebt", "mittag"], true, false),
  product("avocado-bagel", "snacks", "Avocado Bagel", 520, "Stück", "Bagel mit Frischkäse, Tomaten, Rucola und Avocado.", ["A", "G"], ["vegetarisch", "frisch"], true, false),
  product("classique-tomate-ei", "snacks", "Classique Tomate & Ei", 390, "Stück", "Baguette mit Tomaten, Rührei, Remoulade und Salat.", ["A", "C", "G", "F"], ["vegetarisch", "frisch"], true, false),
  product("dinkel-plus-kaese", "snacks", "Dinkel Plus Käse", 380, "Stück", "Dinkelbrötchen mit Schnittkäse und Lollo-Bionda-Salat.", ["A", "G"], ["vegetarisch", "dinkel"], true, false),
  product("wikinger-pute", "snacks", "Wikinger Pute", 450, "Stück", "Sesam-Dreieck mit Putenbrust, Salat und Remoulade.", ["A", "C", "F", "N"], ["proteinreich", "mittag"], true, false),
  product("baeckwich-florida", "snacks", "Bäckwich Florida", 420, "Stück", "Warmer Weizensnack mit Putenbrust und Kräutermayo.", ["A", "C", "N"], ["warm", "mittag"], true, false),
  product("brotzeit-omelett", "snacks", "Brotzeit Omelett", 480, "Stück", "Krustenbrotscheibe mit Omelett, Tomaten und Frühlingszwiebeln.", ["A", "C", "G"], ["warm", "proteinreich"], true, false),
  product("classique-frikadelle", "snacks", "Classique Frikadelle", 450, "Stück", "Baguette mit Geflügelfrikadelle, Remoulade und Krautsalat.", ["A", "C", "F"], ["deftig", "beliebt"], true, false),
  product("classique-pute", "snacks", "Classique Pute", 420, "Stück", "Knuspriges Baguette mit Putenbrust und Remoulade.", ["A", "C", "F"], ["klassiker", "mittag"], true, false),
  product("erdbeer-vanille", "fineGoods", "Erdbeer-Vanille-Fruchtaufstrich", 490, "220g", "Hausgemachter Aufstrich mit Erdbeeren und Bourbon-Vanille.", [], ["geschenk", "hausgemacht", "vegan"], false, true),
  product("habichtswald-honig", "fineGoods", "Honig aus Habichtswald", 690, "250g", "Blütenhonig vom regionalen Imker.", [], ["regional", "geschenk"], false, true),
  product("kaffee-bohnen", "fineGoods", "Caffè Crema Mild Bohnen", 1290, "500g", "Milde Arabica-Bohnen für zu Hause.", [], ["kaffee", "vegan"], false, true),
  product("knabbermix", "fineGoods", "Aue-Knabbermix", 390, "180g", "Geröstete Nüsse, Kerne und Saaten für die Brotzeit.", ["H", "N"], ["snack", "geschenk"], false, true),
  product("backmischung-sauerteig", "fineGoods", "Sauerteig-Backmischung", 790, "750g", "Backmischung für ein mildes Sauerteigbrot zu Hause.", ["A"], ["backmischung", "geschenk"], false, true),
  product("geschenkkorb", "fineGoods", "Aue-Geschenkkorb", 2990, "Korb", "Brotzeit-Geschenk mit Aufstrich, Kaffee und Knabbermischung.", ["A", "H"], ["geschenk", "premium"], false, true),
];

function product(
  id: string,
  category: Product["category"],
  name: string,
  priceCents: number,
  unit: string,
  description: string,
  allergens: Product["allergens"],
  tags: string[],
  preorder: boolean,
  shop: boolean,
): Product {
  return {
    id,
    category,
    name,
    description,
    imageUrl: PRODUCT_IMAGES[id],
    priceCents,
    unit,
    ingredients: [],
    allergens,
    tags,
    preorder,
    shop,
  };
}
